"""sector_groups.py — groups the granular "industry" values (see
IBApp.get_forward_pe / symbols.json "sector" field) into the 11 broad
sectors Yahoo Finance itself uses (Technology, Financial Services,
Healthcare, Consumer Cyclical, Consumer Defensive, Industrials, Energy,
Basic Materials, Real Estate, Utilities, Communication Services).

Python port of web/src/sectorGroups.js -- kept in sync BY HAND (same
"no shared layer across the Python/JS boundary" reasoning main.py's own
CANDLESTICK_TOP_N duplication comment gives; there's no shared module to
import this from on both sides). Used by modules/simulations.py's
industry-peer-group fallback (too few peers in the granular industry ->
widen to the whole broad sector instead).
"""

EXACT = {
    "Advertising Agencies": "Communication Services",
    "Aerospace & Defense": "Industrials",
    "Agricultural Inputs": "Basic Materials",
    "Airlines": "Industrials",
    "Airports & Air Services": "Industrials",
    "Aluminum": "Basic Materials",
    "Apparel Manufacturing": "Consumer Cyclical",
    "Apparel Retail": "Consumer Cyclical",
    "Asset Management": "Financial Services",
    "Auto & Truck Dealerships": "Consumer Cyclical",
    "Auto Manufacturers": "Consumer Cyclical",
    "Auto Parts": "Consumer Cyclical",
    "Banks - Diversified": "Financial Services",
    "Banks - Regional": "Financial Services",
    "Beverages - Brewers": "Consumer Defensive",
    "Beverages - Non-Alcoholic": "Consumer Defensive",
    "Beverages - Wineries & Distilleries": "Consumer Defensive",
    "Biotechnology": "Healthcare",
    "Broadcasting": "Communication Services",
    "Building Materials": "Basic Materials",
    "Building Products & Equipment": "Industrials",
    "Business Equipment & Supplies": "Industrials",
    "Capital Markets": "Financial Services",
    "Chemicals": "Basic Materials",
    "Coking Coal": "Energy",
    "Communication Equipment": "Technology",
    "Computer Hardware": "Technology",
    "Confectioners": "Consumer Defensive",
    "Conglomerates": "Industrials",
    "Consulting Services": "Industrials",
    "Consumer Electronics": "Technology",
    "Copper": "Basic Materials",
    "Credit Services": "Financial Services",
    "Department Stores": "Consumer Cyclical",
    "Diagnostics & Research": "Healthcare",
    "Discount Stores": "Consumer Defensive",
    "Drug Manufacturers - General": "Healthcare",
    "Drug Manufacturers - Specialty & Generic": "Healthcare",
    "Education & Training Services": "Consumer Defensive",
    "Electrical Equipment & Parts": "Industrials",
    "Electronic Components": "Technology",
    "Electronic Gaming & Multimedia": "Communication Services",
    "Electronics & Computer Distribution": "Technology",
    "Engineering & Construction": "Industrials",
    "Entertainment": "Communication Services",
    "Farm & Heavy Construction Machinery": "Industrials",
    "Farm Products": "Consumer Defensive",
    "Financial Conglomerates": "Financial Services",
    "Financial Data & Stock Exchanges": "Financial Services",
    "Food Distribution": "Consumer Defensive",
    "Footwear & Accessories": "Consumer Cyclical",
    "Furnishings, Fixtures & Appliances": "Consumer Cyclical",
    "Gambling": "Consumer Cyclical",
    "Gold": "Basic Materials",
    "Grocery Stores": "Consumer Defensive",
    "Health Information Services": "Healthcare",
    "Healthcare Plans": "Healthcare",
    "Home Improvement Retail": "Consumer Cyclical",
    "Household & Personal Products": "Consumer Defensive",
    "Industrial Distribution": "Industrials",
    "Information Technology Services": "Technology",
    "Infrastructure Operations": "Industrials",
    "Insurance - Diversified": "Financial Services",
    "Insurance - Life": "Financial Services",
    "Insurance - Property & Casualty": "Financial Services",
    "Insurance - Reinsurance": "Financial Services",
    "Insurance - Specialty": "Financial Services",
    "Insurance Brokers": "Financial Services",
    "Integrated Freight & Logistics": "Industrials",
    "Internet Content & Information": "Communication Services",
    "Internet Retail": "Consumer Cyclical",
    "Leisure": "Consumer Cyclical",
    "Lodging": "Consumer Cyclical",
    "Lumber & Wood Production": "Basic Materials",
    "Luxury Goods": "Consumer Cyclical",
    "Marine Shipping": "Industrials",
    "Medical Care Facilities": "Healthcare",
    "Medical Devices": "Healthcare",
    "Medical Distribution": "Healthcare",
    "Medical Instruments & Supplies": "Healthcare",
    "Metal Fabrication": "Industrials",
    "Mortgage Finance": "Financial Services",
    "Oil & Gas Drilling": "Energy",
    "Oil & Gas E&P": "Energy",
    "Oil & Gas Equipment & Services": "Energy",
    "Oil & Gas Integrated": "Energy",
    "Oil & Gas Midstream": "Energy",
    "Oil & Gas Refining & Marketing": "Energy",
    "Other Industrial Metals & Mining": "Basic Materials",
    "Other Precious Metals & Mining": "Basic Materials",
    "Packaged Foods": "Consumer Defensive",
    "Packaging & Containers": "Consumer Cyclical",
    "Paper & Paper Products": "Basic Materials",
    "Personal Services": "Consumer Cyclical",
    "Pollution & Treatment Controls": "Industrials",
    "Publishing": "Communication Services",
    "REIT - Diversified": "Real Estate",
    "REIT - Healthcare Facilities": "Real Estate",
    "REIT - Hotel & Motel": "Real Estate",
    "REIT - Industrial": "Real Estate",
    "REIT - Mortgage": "Real Estate",
    "REIT - Office": "Real Estate",
    "REIT - Residential": "Real Estate",
    "REIT - Retail": "Real Estate",
    "REIT - Specialty": "Real Estate",
    "Railroads": "Industrials",
    "Real Estate - Development": "Real Estate",
    "Real Estate - Diversified": "Real Estate",
    "Real Estate Services": "Real Estate",
    "Recreational Vehicles": "Consumer Cyclical",
    "Rental & Leasing Services": "Industrials",
    "Residential Construction": "Consumer Cyclical",
    "Resorts & Casinos": "Consumer Cyclical",
    "Restaurants": "Consumer Cyclical",
    "Scientific & Technical Instruments": "Technology",
    "Security & Protection Services": "Industrials",
    "Semiconductor Equipment & Materials": "Technology",
    "Semiconductors": "Technology",
    "Software - Application": "Technology",
    "Software - Infrastructure": "Technology",
    "Solar": "Technology",
    "Specialty Business Services": "Industrials",
    "Specialty Chemicals": "Basic Materials",
    "Specialty Industrial Machinery": "Industrials",
    "Specialty Retail": "Consumer Cyclical",
    "Staffing & Employment Services": "Industrials",
    "Steel": "Basic Materials",
    "Telecom Services": "Communication Services",
    "Textile Manufacturing": "Consumer Cyclical",
    "Thermal Coal": "Energy",
    "Tobacco": "Consumer Defensive",
    "Tools & Accessories": "Industrials",
    "Travel Services": "Consumer Cyclical",
    "Trucking": "Industrials",
    "Uranium": "Energy",
    "Utilities - Diversified": "Utilities",
    "Utilities - Independent Power Producers": "Utilities",
    "Utilities - Regulated Electric": "Utilities",
    "Utilities - Regulated Gas": "Utilities",
    "Utilities - Regulated Water": "Utilities",
    "Utilities - Renewable": "Utilities",
    "Waste Management": "Industrials",
}

# Substring fallbacks for any industry not in the exact map above -- same
# list, same order, as web/src/sectorGroups.js's own KEYWORD_FALLBACKS.
KEYWORD_FALLBACKS = [
    ("software", "Technology"),
    ("semiconductor", "Technology"),
    ("bank", "Financial Services"),
    ("insurance", "Financial Services"),
    ("reit", "Real Estate"),
    ("real estate", "Real Estate"),
    ("oil & gas", "Energy"),
    ("coal", "Energy"),
    ("uranium", "Energy"),
    ("auto", "Consumer Cyclical"),
    ("retail", "Consumer Cyclical"),
    ("restaurant", "Consumer Cyclical"),
    ("utilit", "Utilities"),
    ("telecom", "Communication Services"),
    ("media", "Communication Services"),
    ("drug", "Healthcare"),
    ("pharma", "Healthcare"),
    ("medical", "Healthcare"),
    ("biotech", "Healthcare"),
    ("health", "Healthcare"),
    ("mining", "Basic Materials"),
    ("metal", "Basic Materials"),
    ("chemical", "Basic Materials"),
    ("financial", "Financial Services"),
    ("asset", "Financial Services"),
    ("technology", "Technology"),
    ("internet", "Communication Services"),
]

DEFAULT_GROUP = "Other"


def get_sector_group(industry):
    if not industry:
        return DEFAULT_GROUP
    if industry in EXACT:
        return EXACT[industry]
    lower = industry.lower()
    for keyword, group in KEYWORD_FALLBACKS:
        if keyword in lower:
            return group
    return DEFAULT_GROUP
