import { useEffect, useState, type ReactNode } from 'react'
import MathsVariablesTable from '../components/MathsVariablesTable'

// The Maths tab -- a static walkthrough of modules/simulations.py's own
// EPS-driven Monte Carlo methodology, explaining exactly what produces
// simPrice/simReturn (the numbers every other tab's "Fwd PE (exp)"/
// "Revenue growth (exp)"/target-portfolio Sharpe ultimately trace back
// to). Content lives in public/maths.json (explicit instruction: a JSON
// file defining each paragraph, not hardcoded JSX) -- this component is a
// thin fetch + render, same "own fetch, no logic of its own beyond
// formatting" pattern as ScoringFormulaTable/DatasetTable. No Python
// involvement at all (unlike every other public/*.json this app serves,
// which sync-data copies from data/output/*.json) -- this is hand-authored
// frontend content, so it lives directly in web/public and is edited
// there, not regenerated by any `main.py` command.
//
// Schema: {title, subtitle, sections: [{heading, blocks: [...]}]}. Each
// block is one of:
//   {type: "paragraph", text}  -- inline `code` and **bold** supported
//   {type: "list", items}      -- same inline formatting per item
//   {type: "formula", code}    -- rendered verbatim in a <pre>; only the colour
//                                  tokens below are parsed
//   {type: "table", headers, rows} -- cells support the same inline formatting
//
// Colour code (explicit instruction), usable in paragraphs, list items, table
// cells and formulas:  {{raw:text}} yellow = raw downloaded data,
// {{calc:text}} orange = calculated variable, {{out:text}} green = final output.
// Can drift out of sync with modules/simulations.py's own formulas if
// that module changes without this file being updated too -- see that
// module directly for the authoritative version if anything here looks
// stale.

interface Block {
  type: 'paragraph' | 'list' | 'formula' | 'table'
  text?: string
  items?: string[]
  code?: string
  headers?: string[]
  rows?: string[][]
}

interface Section {
  heading: string
  blocks: Block[]
}

interface MathsDoc {
  title: string
  subtitle: string
  sections: Section[]
}

// Splits `text` on colour tokens, `code` spans and **bold** spans, rendering each
// as the matching element and everything else as plain text. Colour tokens may
// wrap code/bold (rendered recursively).
const TOKEN_RE = /(\{\{(?:raw|calc|out):[\s\S]*?\}\}|`[^`]+`|\*\*[^*]+\*\*)/g
function renderInline(text: string, withInline = true): ReactNode[] {
  const parts = text.split(TOKEN_RE).filter((p) => p !== '')
  return parts.map((part, i) => {
    const color = part.match(/^\{\{(raw|calc|out):([\s\S]*)\}\}$/)
    if (color) {
      return (
        <span key={i} className={`maths-${color[1]}`}>
          {renderInline(color[2], withInline)}
        </span>
      )
    }
    if (withInline && part.startsWith('`') && part.endsWith('`')) {
      return <code key={i}>{part.slice(1, -1)}</code>
    }
    if (withInline && part.startsWith('**') && part.endsWith('**')) {
      return <strong key={i}>{part.slice(2, -2)}</strong>
    }
    return <span key={i}>{part}</span>
  })
}

function BlockView({ block }: { block: Block }) {
  if (block.type === 'formula') {
    return <pre>{renderInline(block.code || '', false)}</pre>
  }
  if (block.type === 'table') {
    return (
      <div className="maths-table-scroll">
        <table>
          <thead>
            <tr>
              {(block.headers || []).map((h, i) => (
                <th key={i}>{renderInline(h)}</th>
              ))}
            </tr>
          </thead>
          <tbody>
            {(block.rows || []).map((row, i) => (
              <tr key={i}>
                {row.map((cell, j) => (
                  <td key={j}>{renderInline(cell)}</td>
                ))}
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    )
  }
  if (block.type === 'list') {
    return (
      <ul>
        {(block.items || []).map((item, i) => (
          <li key={i}>{renderInline(item)}</li>
        ))}
      </ul>
    )
  }
  return <p>{renderInline(block.text || '')}</p>
}

export default function MathsView() {
  const [doc, setDoc] = useState<MathsDoc | null>(null)
  const [error, setError] = useState(false)
  const [tab, setTab] = useState<'formulas' | 'variables'>('formulas')

  useEffect(() => {
    fetch('/maths.json')
      .then((r) => (r.ok ? r.json() : Promise.reject()))
      .then(setDoc)
      .catch(() => setError(true))
  }, [])

  return (
    <div className="positions-page dataset-page">
      <header className="masthead">
        <div className="title-block">
          <h1>{doc?.title || 'Maths'}</h1>
          {doc?.subtitle && <p>{doc.subtitle}</p>}
        </div>
      </header>

      <div className="recommendation-tabs">
        <button
          type="button"
          className={`recommendation-tab-btn${tab === 'formulas' ? ' active' : ''}`}
          onClick={() => setTab('formulas')}
        >
          Formulas
        </button>
        <button
          type="button"
          className={`recommendation-tab-btn${tab === 'variables' ? ' active' : ''}`}
          onClick={() => setTab('variables')}
        >
          Data variables
        </button>
      </div>

      {tab === 'formulas' && (
        <div className="maths-legend">
          <span>Colour code:</span>
          <span className="maths-raw">yellow = raw downloaded data</span>
          <span className="maths-calc">orange = calculated variable</span>
          <span className="maths-out">green = final output</span>
        </div>
      )}

      {tab === 'variables' && <MathsVariablesTable />}
      {tab === 'formulas' && error && <div className="asset-card">Couldn't load maths.json.</div>}
      {tab === 'formulas' && !error && !doc && <div className="asset-card">Loading…</div>}

      {tab === 'formulas' && doc?.sections.map((section, i) => (
        <div className="asset-card" key={i}>
          <h2>{section.heading}</h2>
          {section.blocks.map((block, j) => (
            <BlockView block={block} key={j} />
          ))}
        </div>
      ))}
    </div>
  )
}
