import { useEffect, useState } from 'react'

// The Maths tab -- a static walkthrough of modules/simulations.py's own
// EPS-driven Monte Carlo methodology, explaining exactly what produces
// simPrice/simReturn (the numbers every other tab's "Fwd PE (exp)"/
// "Revenue growth (exp)"/target-portfolio Sharpe ultimately trace back
// to). Content lives in public/maths.json (explicit instruction: a JSON
// file defining each paragraph, not hardcoded JSX) -- this component is a
// thin fetch + render, same "own fetch, no logic of its own beyond
// formatting" pattern as ScoringFormulaTable/DatasetTable. No Python
// involvement at all (unlike every other public/*.json this app serves,
// which sync-data copies from data/output/*.json) -- this is hand-authored
// frontend content, so it lives directly in web/public and is edited
// there, not regenerated by any `main.py` command.
//
// Schema: {title, subtitle, sections: [{heading, blocks: [...]}]}. Each
// block is one of:
//   {type: "paragraph", text}  -- inline `code` and **bold** supported
//   {type: "list", items}      -- same inline formatting per item
//   {type: "formula", code}    -- rendered verbatim in a <pre>, no inline
//                                  parsing (it's already code)
// Can drift out of sync with modules/simulations.py's own formulas if
// that module changes without this file being updated too -- see that
// module directly for the authoritative version if anything here looks
// stale.

interface Block {
  type: 'paragraph' | 'list' | 'formula'
  text?: string
  items?: string[]
  code?: string
}

interface Section {
  heading: string
  blocks: Block[]
}

interface MathsDoc {
  title: string
  subtitle: string
  sections: Section[]
}

// Splits `text` on `code` spans and **bold** spans, rendering each as the
// matching element and everything else as plain text -- the only two
// inline styles this content needs (see the schema comment above).
function renderInline(text: string) {
  const parts = text.split(/(`[^`]+`|\*\*[^*]+\*\*)/g).filter((p) => p !== '')
  return parts.map((part, i) => {
    if (part.startsWith('`') && part.endsWith('`')) {
      return <code key={i}>{part.slice(1, -1)}</code>
    }
    if (part.startsWith('**') && part.endsWith('**')) {
      return <strong key={i}>{part.slice(2, -2)}</strong>
    }
    return <span key={i}>{part}</span>
  })
}

function BlockView({ block }: { block: Block }) {
  if (block.type === 'formula') {
    return <pre>{block.code}</pre>
  }
  if (block.type === 'list') {
    return (
      <ul>
        {(block.items || []).map((item, i) => (
          <li key={i}>{renderInline(item)}</li>
        ))}
      </ul>
    )
  }
  return <p>{renderInline(block.text || '')}</p>
}

export default function MathsView() {
  const [doc, setDoc] = useState<MathsDoc | null>(null)
  const [error, setError] = useState(false)

  useEffect(() => {
    fetch('/maths.json')
      .then((r) => (r.ok ? r.json() : Promise.reject()))
      .then(setDoc)
      .catch(() => setError(true))
  }, [])

  return (
    <div className="positions-page dataset-page">
      <header className="masthead">
        <div className="title-block">
          <h1>{doc?.title || 'Maths'}</h1>
          {doc?.subtitle && <p>{doc.subtitle}</p>}
        </div>
      </header>

      {error && <div className="asset-card">Couldn't load maths.json.</div>}
      {!error && !doc && <div className="asset-card">Loading…</div>}

      {doc?.sections.map((section, i) => (
        <div className="asset-card" key={i}>
          <h2>{section.heading}</h2>
          {section.blocks.map((block, j) => (
            <BlockView block={block} key={j} />
          ))}
        </div>
      ))}
    </div>
  )
}
