import {
  Ambulance, Anvil, Beaker, Boxes, Briefcase, Building2, Candy, Car, ChefHat, ClipboardList,
  Cloud, Code2, Cog, Computer, Cpu, CreditCard, Dice5, Drill, FlaskConical, Factory, Film, Footprints, Fuel,
  Gamepad2, Gem, Globe, GlassWater, Hammer, HardHat, Handshake, HeartHandshake,
  HeartPulse, Home, Hotel, LandPlot, Landmark, Leaf, MapPin, Megaphone, Microscope,
  Monitor, Newspaper, Package2, Palmtree, Pickaxe, Pill, Plane, Radio, Recycle,
  Repeat, Rocket, Scissors, Server, ShieldCheck, ShoppingBag, ShoppingCart,
  Smartphone, Sofa, Sprout, SprayCan, Store, Stethoscope, Sun, Syringe, Tractor,
  TrainFront, TrendingUp, Truck, UtensilsCrossed, Warehouse, Wheat, Wifi, Wrench,
  Zap, Building,
} from 'lucide-react'

// Exact industry -> icon, keyed on the values yfinance's "industry" field
// returns (see IBApp.get_forward_pe / symbols.json "sector" field).
const EXACT = {
  // Broad sector-group names (see sectorGroups.js's getSectorGroup) — the
  // Positions tab groups by these directly, distinct from every other key
  // below (a granular yfinance "industry" string), so this branch only
  // ever fires for that one usage, never for PeTable.jsx's per-industry icon.
  'Technology': Computer,
  'Energy': Drill,
  'Healthcare': Ambulance,
  'Industrials': Factory,
  'Advertising Agencies': Megaphone,
  'Aerospace & Defense': Rocket,
  'Agricultural Inputs': Sprout,
  'Airlines': Plane,
  'Aluminum': Pickaxe,
  'Apparel Retail': ShoppingBag,
  'Asset Management': TrendingUp,
  'Auto & Truck Dealerships': Car,
  'Auto Manufacturers': Car,
  'Auto Parts': Wrench,
  'Beverages - Non-Alcoholic': GlassWater,
  'Biotechnology': FlaskConical,
  'Building Materials': Hammer,
  'Building Products & Equipment': Hammer,
  'Communication Equipment': Radio,
  'Computer Hardware': Monitor,
  'Confectioners': Candy,
  'Conglomerates': Building,
  'Consulting Services': Briefcase,
  'Consumer Cyclical': ShoppingBag,
  'Consumer Electronics': Smartphone,
  'Copper': Pickaxe,
  'Credit Services': CreditCard,
  'Diagnostics & Research': Microscope,
  'Discount Stores': ShoppingCart,
  'Drug Manufacturers - General': Pill,
  'Drug Manufacturers - Specialty & Generic': Pill,
  'Electrical Equipment & Parts': Zap,
  'Electronic Components': Cpu,
  'Electronic Gaming & Multimedia': Gamepad2,
  'Engineering & Construction': HardHat,
  'Entertainment': Film,
  'Farm & Heavy Construction Machinery': Tractor,
  'Farm Products': Wheat,
  'Financial Data & Stock Exchanges': TrendingUp,
  'Food Distribution': Truck,
  'Footwear & Accessories': Footprints,
  'Furnishings, Fixtures & Appliances': Sofa,
  'Gambling': Dice5,
  'Gold': Pickaxe,
  'Grocery Stores': ShoppingCart,
  'Health Information Services': ClipboardList,
  'Healthcare Plans': HeartHandshake,
  'Home Improvement Retail': Home,
  'Household & Personal Products': SprayCan,
  'Industrial Distribution': Boxes,
  'Information Technology Services': Server,
  'Insurance - Diversified': ShieldCheck,
  'Insurance - Life': ShieldCheck,
  'Insurance - Property & Casualty': ShieldCheck,
  'Insurance - Specialty': ShieldCheck,
  'Insurance Brokers': Handshake,
  'Integrated Freight & Logistics': Truck,
  'Internet Content & Information': Globe,
  'Internet Retail': ShoppingCart,
  'Leisure': Palmtree,
  'Lodging': Hotel,
  'Luxury Goods': Gem,
  'Medical Care Facilities': Stethoscope,
  'Medical Devices': HeartPulse,
  'Medical Distribution': Package2,
  'Medical Instruments & Supplies': Syringe,
  'Metal Fabrication': Anvil,
  'Oil & Gas E&P': Fuel,
  'Oil & Gas Equipment & Services': Fuel,
  'Oil & Gas Integrated': Fuel,
  'Oil & Gas Midstream': Fuel,
  'Oil & Gas Refining & Marketing': Fuel,
  'Packaged Foods': ChefHat,
  'Packaging & Containers': Package2,
  'Pollution & Treatment Controls': Recycle,
  'Publishing': Newspaper,
  'REIT - Diversified': Building2,
  'REIT - Healthcare Facilities': Building2,
  'REIT - Hotel & Motel': Hotel,
  'REIT - Industrial': Warehouse,
  'REIT - Office': Building2,
  'REIT - Residential': Home,
  'REIT - Retail': Store,
  'REIT - Specialty': Building2,
  'Railroads': TrainFront,
  'Real Estate Services': LandPlot,
  'Rental & Leasing Services': Repeat,
  'Residential Construction': Home,
  'Resorts & Casinos': Palmtree,
  'Restaurants': UtensilsCrossed,
  'Scientific & Technical Instruments': Microscope,
  'Semiconductor Equipment & Materials': Cpu,
  'Semiconductors': Cpu,
  'Software - Application': Code2,
  'Software - Infrastructure': Cloud,
  'Solar': Sun,
  'Specialty Business Services': Briefcase,
  'Specialty Chemicals': Beaker,
  'Specialty Industrial Machinery': Cog,
  'Specialty Retail': Store,
  'Telecom Services': Wifi,
  'Textile Manufacturing': Scissors,
  'Tobacco': Leaf,
  'Travel Services': MapPin,
  'Trucking': Truck,
  'Utilities - Independent Power Producers': Zap,
  'Utilities - Regulated Electric': Zap,
  'Waste Management': Recycle,
}

// Substring fallbacks for any industry not in the exact map above (e.g. a
// label yfinance introduces later, or one that slipped through uncurated).
const KEYWORD_FALLBACKS = [
  ['software', Code2],
  ['semiconductor', Cpu],
  ['bank', Landmark],
  ['insurance', ShieldCheck],
  ['reit', Building2],
  ['oil & gas', Fuel],
  ['auto', Car],
  ['drug', Pill],
  ['pharma', Pill],
  ['medical', HeartPulse],
  ['biotech', FlaskConical],
  ['retail', Store],
  ['restaurant', UtensilsCrossed],
  ['utilit', Zap],
  ['telecom', Wifi],
  ['airline', Plane],
  ['construction', HardHat],
  ['chemical', Beaker],
  ['metal', Anvil],
  ['real estate', LandPlot],
  ['financial', TrendingUp],
  ['asset', TrendingUp],
  ['technology', Server],
  ['internet', Globe],
]

const DEFAULT_ICON = Briefcase

export function getSectorIcon(sector) {
  if (!sector) return DEFAULT_ICON
  if (EXACT[sector]) return EXACT[sector]
  const lower = sector.toLowerCase()
  for (const [keyword, Icon] of KEYWORD_FALLBACKS) {
    if (lower.includes(keyword)) return Icon
  }
  return DEFAULT_ICON
}
