import { useEffect, useMemo, useState } from 'react'

// Maths > "Data variables" tab: every variable the app downloads (yfinance,
// Eulerpool, FINRA, SEC) and where code reads it; a red cross when nothing
// does. Content is public/maths_variables.json, generated by
// `python -m modules.variable_catalog` (re-run it after changing the
// pipeline -- it is hand-checked for ambiguous names, see that module).

interface VariableRow {
  source: string
  dataset: string
  variable: string
  note: string
  usedIn: string[]
  used: boolean
}

const SOURCES = ['All', 'yfinance', 'Eulerpool', 'FINRA', 'SEC']

export default function MathsVariablesTable() {
  const [rows, setRows] = useState<VariableRow[] | null>(null)
  const [error, setError] = useState(false)
  const [source, setSource] = useState('All')
  const [unusedOnly, setUnusedOnly] = useState(false)
  const [query, setQuery] = useState('')

  useEffect(() => {
    fetch('/maths_variables.json')
      .then((r) => (r.ok ? r.json() : Promise.reject()))
      .then((d: { rows: VariableRow[] }) => setRows(d.rows))
      .catch(() => setError(true))
  }, [])

  const shown = useMemo(() => {
    const q = query.trim().toLowerCase()
    return (rows ?? []).filter(
      (r) =>
        (source === 'All' || r.source === source) &&
        (!unusedOnly || !r.used) &&
        (!q || `${r.variable} ${r.dataset} ${r.usedIn.join(' ')}`.toLowerCase().includes(q)),
    )
  }, [rows, source, unusedOnly, query])

  const counts = useMemo(() => {
    const out: Record<string, { used: number; total: number }> = {}
    for (const r of rows ?? []) {
      const c = (out[r.source] ??= { used: 0, total: 0 })
      c.total += 1
      if (r.used) c.used += 1
    }
    return out
  }, [rows])

  if (error) return <div className="asset-card">Couldn't load maths_variables.json.</div>
  if (!rows) return <div className="asset-card">Loading…</div>

  return (
    <div className="asset-card">
      <h2>Data variables — what we download and where it is used</h2>
      <p className="status-row">
        "Used" means read by code (a score, a simulation, a derived column or a page), directly or to build another
        column. <span className="bad">✗</span> = downloaded but nothing reads it (or it is only copied into
        screen_data.csv). Regenerate with <code>python -m modules.variable_catalog</code>.
      </p>
      <div className="maths-vars-filters">
        {SOURCES.map((s) => (
          <button
            key={s}
            type="button"
            className={`tab-btn${source === s ? ' active' : ''}`}
            onClick={() => setSource(s)}
          >
            {s}
            {s !== 'All' && counts[s] ? ` (${counts[s].used}/${counts[s].total})` : ''}
          </button>
        ))}
        <label>
          <input type="checkbox" checked={unusedOnly} onChange={(e) => setUnusedOnly(e.target.checked)} /> Unused only
        </label>
        <input
          type="search"
          placeholder="Search variable, dataset or use…"
          value={query}
          onChange={(e) => setQuery(e.target.value)}
        />
      </div>
      <div className="maths-vars-scroll">
        <table>
          <thead>
            <tr>
              <th className="col-left">Source</th>
              <th className="col-left">Dataset</th>
              <th className="col-left">Variable</th>
              <th className="col-left">Where it is used</th>
            </tr>
          </thead>
          <tbody>
            {shown.length === 0 && (
              <tr className="empty-row">
                <td colSpan={4}>No variables match.</td>
              </tr>
            )}
            {shown.map((r, i) => (
              <tr key={`${r.dataset}-${r.variable}-${i}`}>
                <td className="col-left">{r.source}</td>
                <td className="col-left">{r.dataset}</td>
                <td className="col-left">
                  <code>{r.variable}</code>
                  {r.note && <span className="status-row"> {r.note}</span>}
                </td>
                <td className="col-left">
                  {r.used ? (
                    <ul className="maths-vars-uses">
                      {r.usedIn.slice(0, 6).map((u) => (
                        <li key={u}>{u}</li>
                      ))}
                      {r.usedIn.length > 6 && <li>+{r.usedIn.length - 6} more</li>}
                    </ul>
                  ) : (
                    <span className="bad" title="Downloaded but not used anywhere">✗ not used</span>
                  )}
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </div>
  )
}
